/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminProductsRouteImport } from './routes/_admin/products'
import { Route as AdminMachinesRouteImport } from './routes/_admin/machines'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/_admin/customers'
import { Route as AdminCreateCustomerRouteImport } from './routes/_admin/create-customer'
import { Route as AdminContractsRouteImport } from './routes/_admin/contracts'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesRoute = AdminMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateCustomerRoute = AdminCreateCustomerRouteImport.update({
  id: '/create-customer',
  path: '/create-customer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/sign-in': typeof SignInRoute
  '/contracts': typeof AdminContractsRoute
  '/create-customer': typeof AdminCreateCustomerRoute
  '/customers': typeof AdminCustomersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/machines': typeof AdminMachinesRoute
  '/products': typeof AdminProductsRoute
  '/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/contracts': typeof AdminContractsRoute
  '/create-customer': typeof AdminCreateCustomerRoute
  '/customers': typeof AdminCustomersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/machines': typeof AdminMachinesRoute
  '/products': typeof AdminProductsRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_admin/contracts': typeof AdminContractsRoute
  '/_admin/create-customer': typeof AdminCreateCustomerRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/machines': typeof AdminMachinesRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/contracts'
    | '/create-customer'
    | '/customers'
    | '/dashboard'
    | '/machines'
    | '/products'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/contracts'
    | '/create-customer'
    | '/customers'
    | '/dashboard'
    | '/machines'
    | '/products'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/sign-in'
    | '/_admin/contracts'
    | '/_admin/create-customer'
    | '/_admin/customers'
    | '/_admin/dashboard'
    | '/_admin/machines'
    | '/_admin/products'
    | '/_admin/users'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/machines': {
      id: '/_admin/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AdminMachinesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/create-customer': {
      id: '/_admin/create-customer'
      path: '/create-customer'
      fullPath: '/create-customer'
      preLoaderRoute: typeof AdminCreateCustomerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/contracts': {
      id: '/_admin/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContractsRoute: typeof AdminContractsRoute
  AdminCreateCustomerRoute: typeof AdminCreateCustomerRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMachinesRoute: typeof AdminMachinesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContractsRoute: AdminContractsRoute,
  AdminCreateCustomerRoute: AdminCreateCustomerRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMachinesRoute: AdminMachinesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
