/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthHandoffRouteImport } from './routes/auth/handoff'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected/organizations'
import { Route as ProtectedInvitationsRouteImport } from './routes/_protected/invitations'
import { Route as ProtectedOrgSlugRouteRouteImport } from './routes/_protected/$orgSlug/route'
import { Route as ProtectedOrgSlugIndexRouteImport } from './routes/_protected/$orgSlug/index'
import { Route as ProtectedOrgSlugProductsRouteImport } from './routes/_protected/$orgSlug/products'
import { Route as ProtectedOrgSlugMachinesRouteImport } from './routes/_protected/$orgSlug/machines'
import { Route as ProtectedOrgSlugDashboardRouteImport } from './routes/_protected/$orgSlug/dashboard'
import { Route as ProtectedOrgSlugContractsRouteImport } from './routes/_protected/$orgSlug/contracts'
import { Route as ProtectedOrgSlugBusinessesRouteImport } from './routes/_protected/$orgSlug/businesses'
import { Route as ProtectedOrgSlugMachinesMachineIdRouteImport } from './routes/_protected/$orgSlug/machines.$machineId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthHandoffRoute = AuthHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInvitationsRoute = ProtectedInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrgSlugRouteRoute = ProtectedOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrgSlugIndexRoute = ProtectedOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedOrgSlugRouteRoute,
} as any)
const ProtectedOrgSlugProductsRoute =
  ProtectedOrgSlugProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ProtectedOrgSlugRouteRoute,
  } as any)
const ProtectedOrgSlugMachinesRoute =
  ProtectedOrgSlugMachinesRouteImport.update({
    id: '/machines',
    path: '/machines',
    getParentRoute: () => ProtectedOrgSlugRouteRoute,
  } as any)
const ProtectedOrgSlugDashboardRoute =
  ProtectedOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedOrgSlugRouteRoute,
  } as any)
const ProtectedOrgSlugContractsRoute =
  ProtectedOrgSlugContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => ProtectedOrgSlugRouteRoute,
  } as any)
const ProtectedOrgSlugBusinessesRoute =
  ProtectedOrgSlugBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => ProtectedOrgSlugRouteRoute,
  } as any)
const ProtectedOrgSlugMachinesMachineIdRoute =
  ProtectedOrgSlugMachinesMachineIdRouteImport.update({
    id: '/$machineId',
    path: '/$machineId',
    getParentRoute: () => ProtectedOrgSlugMachinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/$orgSlug': typeof ProtectedOrgSlugRouteRouteWithChildren
  '/invitations': typeof ProtectedInvitationsRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/$orgSlug/businesses': typeof ProtectedOrgSlugBusinessesRoute
  '/$orgSlug/contracts': typeof ProtectedOrgSlugContractsRoute
  '/$orgSlug/dashboard': typeof ProtectedOrgSlugDashboardRoute
  '/$orgSlug/machines': typeof ProtectedOrgSlugMachinesRouteWithChildren
  '/$orgSlug/products': typeof ProtectedOrgSlugProductsRoute
  '/$orgSlug/': typeof ProtectedOrgSlugIndexRoute
  '/$orgSlug/machines/$machineId': typeof ProtectedOrgSlugMachinesMachineIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/invitations': typeof ProtectedInvitationsRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/': typeof ProtectedIndexRoute
  '/$orgSlug/businesses': typeof ProtectedOrgSlugBusinessesRoute
  '/$orgSlug/contracts': typeof ProtectedOrgSlugContractsRoute
  '/$orgSlug/dashboard': typeof ProtectedOrgSlugDashboardRoute
  '/$orgSlug/machines': typeof ProtectedOrgSlugMachinesRouteWithChildren
  '/$orgSlug/products': typeof ProtectedOrgSlugProductsRoute
  '/$orgSlug': typeof ProtectedOrgSlugIndexRoute
  '/$orgSlug/machines/$machineId': typeof ProtectedOrgSlugMachinesMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_protected/$orgSlug': typeof ProtectedOrgSlugRouteRouteWithChildren
  '/_protected/invitations': typeof ProtectedInvitationsRoute
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/$orgSlug/businesses': typeof ProtectedOrgSlugBusinessesRoute
  '/_protected/$orgSlug/contracts': typeof ProtectedOrgSlugContractsRoute
  '/_protected/$orgSlug/dashboard': typeof ProtectedOrgSlugDashboardRoute
  '/_protected/$orgSlug/machines': typeof ProtectedOrgSlugMachinesRouteWithChildren
  '/_protected/$orgSlug/products': typeof ProtectedOrgSlugProductsRoute
  '/_protected/$orgSlug/': typeof ProtectedOrgSlugIndexRoute
  '/_protected/$orgSlug/machines/$machineId': typeof ProtectedOrgSlugMachinesMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sign-in'
    | '/$orgSlug'
    | '/invitations'
    | '/organizations'
    | '/auth/handoff'
    | '/$orgSlug/businesses'
    | '/$orgSlug/contracts'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/machines'
    | '/$orgSlug/products'
    | '/$orgSlug/'
    | '/$orgSlug/machines/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sign-in'
    | '/invitations'
    | '/organizations'
    | '/auth/handoff'
    | '/'
    | '/$orgSlug/businesses'
    | '/$orgSlug/contracts'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/machines'
    | '/$orgSlug/products'
    | '/$orgSlug'
    | '/$orgSlug/machines/$machineId'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/sign-in'
    | '/_protected/$orgSlug'
    | '/_protected/invitations'
    | '/_protected/organizations'
    | '/auth/handoff'
    | '/_protected/'
    | '/_protected/$orgSlug/businesses'
    | '/_protected/$orgSlug/contracts'
    | '/_protected/$orgSlug/dashboard'
    | '/_protected/$orgSlug/machines'
    | '/_protected/$orgSlug/products'
    | '/_protected/$orgSlug/'
    | '/_protected/$orgSlug/machines/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/handoff': {
      id: '/auth/handoff'
      path: '/handoff'
      fullPath: '/auth/handoff'
      preLoaderRoute: typeof AuthHandoffRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/invitations': {
      id: '/_protected/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof ProtectedInvitationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$orgSlug': {
      id: '/_protected/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof ProtectedOrgSlugRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$orgSlug/': {
      id: '/_protected/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof ProtectedOrgSlugIndexRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/products': {
      id: '/_protected/$orgSlug/products'
      path: '/products'
      fullPath: '/$orgSlug/products'
      preLoaderRoute: typeof ProtectedOrgSlugProductsRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/machines': {
      id: '/_protected/$orgSlug/machines'
      path: '/machines'
      fullPath: '/$orgSlug/machines'
      preLoaderRoute: typeof ProtectedOrgSlugMachinesRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/dashboard': {
      id: '/_protected/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof ProtectedOrgSlugDashboardRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/contracts': {
      id: '/_protected/$orgSlug/contracts'
      path: '/contracts'
      fullPath: '/$orgSlug/contracts'
      preLoaderRoute: typeof ProtectedOrgSlugContractsRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/businesses': {
      id: '/_protected/$orgSlug/businesses'
      path: '/businesses'
      fullPath: '/$orgSlug/businesses'
      preLoaderRoute: typeof ProtectedOrgSlugBusinessesRouteImport
      parentRoute: typeof ProtectedOrgSlugRouteRoute
    }
    '/_protected/$orgSlug/machines/$machineId': {
      id: '/_protected/$orgSlug/machines/$machineId'
      path: '/$machineId'
      fullPath: '/$orgSlug/machines/$machineId'
      preLoaderRoute: typeof ProtectedOrgSlugMachinesMachineIdRouteImport
      parentRoute: typeof ProtectedOrgSlugMachinesRoute
    }
  }
}

interface ProtectedOrgSlugMachinesRouteChildren {
  ProtectedOrgSlugMachinesMachineIdRoute: typeof ProtectedOrgSlugMachinesMachineIdRoute
}

const ProtectedOrgSlugMachinesRouteChildren: ProtectedOrgSlugMachinesRouteChildren =
  {
    ProtectedOrgSlugMachinesMachineIdRoute:
      ProtectedOrgSlugMachinesMachineIdRoute,
  }

const ProtectedOrgSlugMachinesRouteWithChildren =
  ProtectedOrgSlugMachinesRoute._addFileChildren(
    ProtectedOrgSlugMachinesRouteChildren,
  )

interface ProtectedOrgSlugRouteRouteChildren {
  ProtectedOrgSlugBusinessesRoute: typeof ProtectedOrgSlugBusinessesRoute
  ProtectedOrgSlugContractsRoute: typeof ProtectedOrgSlugContractsRoute
  ProtectedOrgSlugDashboardRoute: typeof ProtectedOrgSlugDashboardRoute
  ProtectedOrgSlugMachinesRoute: typeof ProtectedOrgSlugMachinesRouteWithChildren
  ProtectedOrgSlugProductsRoute: typeof ProtectedOrgSlugProductsRoute
  ProtectedOrgSlugIndexRoute: typeof ProtectedOrgSlugIndexRoute
}

const ProtectedOrgSlugRouteRouteChildren: ProtectedOrgSlugRouteRouteChildren = {
  ProtectedOrgSlugBusinessesRoute: ProtectedOrgSlugBusinessesRoute,
  ProtectedOrgSlugContractsRoute: ProtectedOrgSlugContractsRoute,
  ProtectedOrgSlugDashboardRoute: ProtectedOrgSlugDashboardRoute,
  ProtectedOrgSlugMachinesRoute: ProtectedOrgSlugMachinesRouteWithChildren,
  ProtectedOrgSlugProductsRoute: ProtectedOrgSlugProductsRoute,
  ProtectedOrgSlugIndexRoute: ProtectedOrgSlugIndexRoute,
}

const ProtectedOrgSlugRouteRouteWithChildren =
  ProtectedOrgSlugRouteRoute._addFileChildren(
    ProtectedOrgSlugRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedOrgSlugRouteRoute: typeof ProtectedOrgSlugRouteRouteWithChildren
  ProtectedInvitationsRoute: typeof ProtectedInvitationsRoute
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOrgSlugRouteRoute: ProtectedOrgSlugRouteRouteWithChildren,
  ProtectedInvitationsRoute: ProtectedInvitationsRoute,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthHandoffRoute: typeof AuthHandoffRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthHandoffRoute: AuthHandoffRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
